const fs = require('fs');
const file = 'src/pages/Fees.jsx';
let content = fs.readFileSync(file, 'utf8');

// 1. Add selectedBatch state
content = content.replace(
  'const [selectedMonth, setSelectedMonth] = useState(new Date().toISOString().slice(0, 7));',
  'const [selectedMonth, setSelectedMonth] = useState(new Date().toISOString().slice(0, 7));\n  const [selectedBatch, setSelectedBatch] = useState("All");'
);

// 2. Add batch options
const beforeBatchOptions = '// Compute fee statuses for the selected month\r\n  const studentStatuses = useMemo(() => {\r\n    return students\r\n      .filter(s => {\r\n        // Find if student\'s admission date is after the selected month';

const afterBatchOptions = 'const batchOptions = useMemo(() => {\n    const batches = new Set(students.map(s => s.batchName).filter(Boolean));\n    return ["All", ...Array.from(batches)].sort();\n  }, [students]);\n\n  // Compute fee statuses for the selected month\n  const studentStatuses = useMemo(() => {\n    return students\n      .filter(s => {\n        if (selectedBatch !== "All" && s.batchName !== selectedBatch) return false;\n\n        // Find if student\'s admission date is after the selected month';

content = content.replace(beforeBatchOptions, afterBatchOptions);
content = content.replace(beforeBatchOptions.replace(/\r\n/g, '\n'), afterBatchOptions);

// 3. Update deps
content = content.replace(
  '}, [students, feePayments, selectedMonth]);',
  '}, [students, feePayments, selectedMonth, selectedBatch]);'
);

// 4. Update Mobile UI
const mobileOld = '          {/* Month Selector Box */}\r\n            <div className="relative cursor-pointer">\r\n              <div className="w-full bg-white dark:bg-[#101420] border border-zinc-200/80 dark:border-zinc-800 rounded-2xl px-3.5 py-3 flex items-center justify-between shadow-sm">\r\n                <div className="flex items-center space-x-2.5 min-w-0">\r\n                  <Calendar className="w-4 h-4 text-zinc-400" />\r\n                  <span className="text-xs font-bold text-zinc-900 dark:text-zinc-200">\r\n                    {format(new Date(selectedMonth + \'-01\'), \'MMMM yyyy\')}\r\n                  </span>\r\n                </div>\r\n                <ChevronDown className="w-4 h-4 text-zinc-400 pointer-events-none flex-shrink-0" />\r\n              </div>\r\n              <select\r\n                value={selectedMonth}\r\n                onChange={(e) => setSelectedMonth(e.target.value)}\r\n                className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-10"\r\n              >\r\n                {monthOptions.map((opt) => (\r\n                  <option key={opt.value} value={opt.value}>\r\n                    {opt.label}\r\n                  </option>\r\n                ))}\r\n              </select>\r\n            </div>';

const mobileNew = '            {/* Selectors Row */}\r\n            <div className="flex gap-2">\r\n              {/* Month Selector Box */}\r\n              <div className="relative cursor-pointer flex-1">\r\n                <div className="w-full bg-white dark:bg-[#101420] border border-zinc-200/80 dark:border-zinc-800 rounded-2xl px-3.5 py-3 flex items-center justify-between shadow-sm">\r\n                  <div className="flex items-center space-x-2.5 min-w-0">\r\n                    <Calendar className="w-4 h-4 text-zinc-400" />\r\n                    <span className="text-xs font-bold text-zinc-900 dark:text-zinc-200 truncate">\r\n                      {format(new Date(selectedMonth + \'-01\'), \'MMM yyyy\')}\r\n                    </span>\r\n                  </div>\r\n                  <ChevronDown className="w-4 h-4 text-zinc-400 pointer-events-none flex-shrink-0" />\r\n                </div>\r\n                <select\r\n                  value={selectedMonth}\r\n                  onChange={(e) => setSelectedMonth(e.target.value)}\r\n                  className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-10"\r\n                >\r\n                  {monthOptions.map((opt) => (\r\n                    <option key={opt.value} value={opt.value}>\r\n                      {opt.label}\r\n                    </option>\r\n                  ))}\r\n                </select>\r\n              </div>\r\n\r\n              {/* Batch Selector Box */}\r\n              <div className="relative cursor-pointer flex-1">\r\n                <div className="w-full bg-white dark:bg-[#101420] border border-zinc-200/80 dark:border-zinc-800 rounded-2xl px-3.5 py-3 flex items-center justify-between shadow-sm">\r\n                  <div className="flex items-center space-x-2.5 min-w-0">\r\n                    <Filter className="w-4 h-4 text-zinc-400" />\r\n                    <span className="text-xs font-bold text-zinc-900 dark:text-zinc-200 truncate">\r\n                      {selectedBatch === \'All\' ? \'All Batches\' : selectedBatch}\r\n                    </span>\r\n                  </div>\r\n                  <ChevronDown className="w-4 h-4 text-zinc-400 pointer-events-none flex-shrink-0" />\r\n                </div>\r\n                <select\r\n                  value={selectedBatch}\r\n                  onChange={(e) => setSelectedBatch(e.target.value)}\r\n                  className="absolute inset-0 w-full h-full opacity-0 cursor-pointer z-10"\r\n                >\r\n                  {batchOptions.map((batch) => (\r\n                    <option key={batch} value={batch}>\r\n                      {batch === \'All\' ? \'All Batches\' : batch}\r\n                    </option>\r\n                  ))}\r\n                </select>\r\n              </div>\r\n            </div>';

content = content.replace(mobileOld, mobileNew);
content = content.replace(mobileOld.replace(/\r\n/g, '\n'), mobileNew);

// 5. Update Desktop UI
const desktopOld = '              <div className="flex items-center space-x-3">\r\n                <div className="relative">\r\n                  <select\r\n                    value={selectedMonth}\r\n                    onChange={(e) => setSelectedMonth(e.target.value)}\r\n                    className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 text-zinc-900 dark:text-white font-semibold text-sm rounded-xl px-4 py-2.5 pr-9 appearance-none focus:outline-none focus:ring-2 focus:ring-red-500/20 shadow-sm cursor-pointer"\r\n                  >\r\n                    {monthOptions.map((opt) => (\r\n                      <option key={opt.value} value={opt.value}>\r\n                        {opt.label}\r\n                      </option>\r\n                    ))}\r\n                  </select>\r\n                  <ChevronDown className="w-4 h-4 text-zinc-400 absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none" />\r\n                </div>\r\n              </div>';

const desktopNew = '              <div className="flex items-center space-x-3">\r\n                <div className="relative">\r\n                  <select\r\n                    value={selectedMonth}\r\n                    onChange={(e) => setSelectedMonth(e.target.value)}\r\n                    className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 text-zinc-900 dark:text-white font-semibold text-sm rounded-xl px-4 py-2.5 pr-9 appearance-none focus:outline-none focus:ring-2 focus:ring-red-500/20 shadow-sm cursor-pointer"\r\n                  >\r\n                    {monthOptions.map((opt) => (\r\n                      <option key={opt.value} value={opt.value}>\r\n                        {opt.label}\r\n                      </option>\r\n                    ))}\r\n                  </select>\r\n                  <ChevronDown className="w-4 h-4 text-zinc-400 absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none" />\r\n                </div>\r\n                <div className="relative">\r\n                  <select\r\n                    value={selectedBatch}\r\n                    onChange={(e) => setSelectedBatch(e.target.value)}\r\n                    className="bg-white dark:bg-zinc-900 border border-zinc-200 dark:border-zinc-800 text-zinc-900 dark:text-white font-semibold text-sm rounded-xl px-4 py-2.5 pr-9 appearance-none focus:outline-none focus:ring-2 focus:ring-red-500/20 shadow-sm cursor-pointer"\r\n                  >\r\n                    {batchOptions.map((batch) => (\r\n                      <option key={batch} value={batch}>\r\n                        {batch === \'All\' ? \'All Batches\' : batch}\r\n                      </option>\r\n                    ))}\r\n                  </select>\r\n                  <ChevronDown className="w-4 h-4 text-zinc-400 absolute right-3 top-1/2 -translate-y-1/2 pointer-events-none" />\r\n                </div>\r\n              </div>';

content = content.replace(desktopOld, desktopNew);
content = content.replace(desktopOld.replace(/\r\n/g, '\n'), desktopNew);

content = content.replace('Calendar,', 'Calendar, Filter,');

fs.writeFileSync(file, content, 'utf8');
